# Generated by Django 4.2.6 on 2023-10-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amujApi", "0004_size_product_size"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collections",
            new_name="Collection",
        ),
    ]
